# Generated by Django 3.2.21 on 2023-09-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_profile_picture',
            field=models.ImageField(default='images/misc/profile/default_profile_picture.jpeg', upload_to='images/misc/profile'),
        ),
    ]
